export const ROUTES = {
  home: "/",
  login: "/login",
  signup: "/signup",
  pricing: "/pricing",
  docs: "/docs",
  apps: "/apps",
  templates: "/templates",
  contactSales: "/contact-sales",
  about: "/about",
  dashboard: "/dashboard",
  dashboardWorkflows: "/dashboard/workflows",
  dashboardWorkflowNew: "/dashboard/workflows/new",
  dashboardApps: "/dashboard/apps",
  dashboardAgents: "/dashboard/agents",
  dashboardHistory: "/dashboard/history",
  dashboardSettings: "/dashboard/settings",
  dashboardTables: "/dashboard/tables",
  dashboardForms: "/dashboard/forms",
  dashboardChatbots: "/dashboard/chatbots",
  dashboardCanvas: "/dashboard/canvas",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminWorkflows: "/admin/workflows",
  adminIntegrations: "/admin/integrations",
  adminAudit: "/admin/audit",
  adminSettings: "/admin/settings",
  product: (slug: string) => `/products/${slug}`,
  solution: (slug: string) => `/solutions/${slug}`,
  doc: (slug: string) => `/docs/${slug}`,
  workflow: (id: string) => `/dashboard/workflows/${id}`,
  legal: (slug: string) => `/legal/${slug}`,
  resource: (slug: string) => `/resources/${slug}`,
} as const;

export const PRODUCT_SLUGS = [
  "workflows",
  "agents",
  "chatbots",
  "tables",
  "forms",
  "canvas",
] as const;

export const SOLUTION_SLUGS = [
  "revops",
  "marketing",
  "it",
  "sales",
  "customer-support",
  "enterprise",
] as const;

export const DOC_SLUGS = [
  "getting-started",
  "workflows",
  "integrations",
  "api",
  "security",
] as const;

export const FOOTER_HREF_MAP: Record<string, string> = {
  "AI Workflows": ROUTES.product("workflows"),
  "AI Agents": ROUTES.product("agents"),
  Chatbots: ROUTES.product("chatbots"),
  Tables: ROUTES.product("tables"),
  Forms: ROUTES.product("forms"),
  Canvas: ROUTES.product("canvas"),
  RevOps: ROUTES.solution("revops"),
  Marketing: ROUTES.solution("marketing"),
  IT: ROUTES.solution("it"),
  Sales: ROUTES.solution("sales"),
  "Customer Support": ROUTES.solution("customer-support"),
  Enterprise: ROUTES.solution("enterprise"),
  Blog: ROUTES.resource("blog"),
  "Help Center": ROUTES.docs,
  Templates: ROUTES.templates,
  Webinars: ROUTES.resource("webinars"),
  Community: ROUTES.resource("community"),
  Developers: ROUTES.doc("api"),
  About: ROUTES.about,
  Careers: ROUTES.resource("careers"),
  Press: ROUTES.resource("press"),
  Partners: ROUTES.resource("partners"),
  Contact: ROUTES.contactSales,
  Legal: ROUTES.legal("terms"),
};
